# Generated by Django 4.2.24 on 2025-10-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0002_counterparty_group_paymentsystem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Variability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_dir.flowtype', verbose_name='Тип потока')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='flow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.flowtype', verbose_name='Тип потока'),
        ),
        migrations.AlterField(
            model_name='item',
            name='variability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.variability', verbose_name='Изменчивость'),
        ),
    ]
