# Generated by Django 4.2.24 on 2025-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0003_flowtype_alter_item_group_variability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
