# Generated by Django 4.2.24 on 2025-10-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_dir', '0004_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_dir.counterparty')),
            ],
            options={
                'unique_together': {('counterparty', 'year')},
            },
        ),
    ]
