# Generated by Django 4.2.24 on 2025-10-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0004_frequency'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantsOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_dir.participant')),
            ],
            options={
                'unique_together': {('participant', 'year')},
            },
        ),
    ]
