# Generated by Django 4.2.24 on 2025-10-02 05:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Банк')),
                ('card_number', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.department', verbose_name='Отдел')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employeetype', verbose_name='Тип сотрудника')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.position', verbose_name='Должность')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.status', verbose_name='Статус сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата ОДДС')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма выплаты')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee', verbose_name='Сотрудник')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_as_payer', to='analytics_dir.participant', verbose_name='Плательщик ОТ КУДА')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.paymenttype', verbose_name='Тип выплаты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.project', verbose_name='Проект')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_as_recipient', to='analytics_dir.participant', verbose_name='Плательщик КУДА')),
            ],
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата начисления')),
                ('hourly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Почасовая')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Оклад')),
                ('addition_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Премия/доплаты')),
                ('deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Возвраты/вычеты')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.project', verbose_name='Проект')),
            ],
        ),
    ]
