# Generated by Django 4.2.24 on 2025-10-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0001_initial'),
        ('payroll', '0002_employee_payout_accrual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accrual',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='payout',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_as_recipient', to='analytics_dir.participant', verbose_name='Получатель КУДА'),
        ),
    ]
