# Generated by Django 4.2.24 on 2025-10-06 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_dir', '0002_counterparty_group_paymentsystem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата ОДДС')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('frequency', models.CharField(choices=[('once', 'Разово'), ('2', '2 мес.'), ('3', '3 мес.'), ('4', '4 мес.'), ('5', '5 мес.'), ('6', '6 мес.'), ('7', '7 мес.'), ('8', '8 мес.'), ('9', '9 мес.'), ('10', '10 мес.'), ('11', '11 мес.'), ('12', '12 мес.')], default='once', max_length=5, verbose_name='Частота платежа')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.item', verbose_name='Статья')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата платежа (ОДДС)')),
                ('recognition_date', models.DateField(blank=True, null=True, verbose_name='Дата признания (ОПУ)')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма оплаты')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма комиссии')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.counterparty', verbose_name='Контрагент')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.item', verbose_name='Статья')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acc_as_payer', to='analytics_dir.participant', verbose_name='Плательщик')),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.paymentsystem', verbose_name='Платежная система')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.project', verbose_name='Проект')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_as_recipient', to='analytics_dir.participant', verbose_name='Получатель')),
            ],
        ),
    ]
