# Generated by Django 4.2.24 on 2025-10-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dir', '0004_frequency'),
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalaccounting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics_dir.frequency', verbose_name='Частота платежа'),
        ),
    ]
